version: '3.8'

services:
  test:
    image: ghcr.io/${{ github.repository }}:latest
    container_name: calculator_test
    command: pytest calculator/tests
    volumes:
      - .:/usr/src/app
    environment:
      - ENV2=test2
