version: '3.8'

services:
  app:
    build: .
    container_name: calculator_app

  test:
    build: .
    container_name: calculator_test
    volumes:
      - .:/usr/src/app
    command: pytest calculator/tests
    depends_on:
      - app
