version: '3.8'

services:
  test:
    image: 008003088695.dkr.ecr.eu-central-1.amazonaws.com/cache-repository:cache
    container_name: calculator_test
    command: pytest calculator/tests
    volumes:
      - .:/usr/src/app
    environment:
      - ENV2=test2
