version: '3.11'

services:
  react-app:
    image: react-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    