name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: docker/build-push-action@v5
        with:
          context: ./react-app
          file: ./react-app/Dockerfile
          tags: react-app:latest
          load: true
          cache-from: type=gha,ref=master
          cache-to: type=gha,ref=master,mode=max

      - name: Build and run with docker compose
        working-directory: ./react-app
        run: |
          docker-compose pull
          docker-compose build
          docker-compose up -d
          docker-compose ps
