name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  AWS_REGION: eu-central-1
  ECR_REPO_NAME: cache-repository

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      id: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Check for changes in requirements.txt
      id: check_requirements
      run: |
        git fetch origin master
        REQUIREMENTS_CHANGED=$(git diff --name-only origin/master..HEAD | grep -q 'requirements.txt' && echo 'true' || echo 'false')
        echo "requirements_changed=$REQUIREMENTS_CHANGED" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create and use new docker builder instance
      run: docker buildx create --name docker-builder --use

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPO_NAME: ${{ env.ECR_REPO_NAME }}
      with:
        context: .
        file: Dockerfile
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO_NAME }}:latest
        push: ${{ steps.check_requirements.outputs.requirements_changed == 'true' && 'true' || 'false' }}
        load: true
        builder: docker-builder
        cache-from: type=registry,ref=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO_NAME }}:cache
        cache-to: ${{ steps.check_requirements.outputs.requirements_changed == 'true' && format('type=registry,mode=max,image-manifest=true,oci-mediatypes=true,ref={0}/{1}:cache', env.ECR_REGISTRY, env.ECR_REPO_NAME) || '' }}
        

    # - name: Build docker-compose
    #   id: build
    #   run: |
    #     docker buildx bake --file docker-compose.yaml --file docker-compose-cache.json
    

    - name: Run tests
      env:
        IMAGE_NAME: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO_NAME }}:latest
      run: |
        docker-compose -f docker-compose.tests.yaml run -e ENV1=test1 --rm test